### ISSUE TITLE
import xml job failure == Invalid XPath expression:  Unexpected ''

### ISSUE THREAD

**Issue by herrygoon** [rundeck/rundeck-api-java-client#33]
rundeck:2.5.1 ; dom4j:1.6.1 ; rundeck-api-java-client:13.1
```
 @Test
    public void importJobs2Project() throws Exception {
        DefaultJobsImport jobsImport = new DefaultJobsImport();
        jobsImport.setFileType(FileType.XML);
        jobsImport.setProject("aaa");
        jobsImport.setUuidImportBehavior(RundeckJobsUUIDImportBehavior.REMOVE);
        FileInputStream fis = new FileInputStream(new File("E:\\Install_Software_powershell.xml"));
        jobsImport.setStream(fis);
        rundeckClient.importJobs(jobsImport);
    }
```
org.dom4j.InvalidXPathException: Invalid XPath expression:  Unexpected ''
	at org.dom4j.xpath.DefaultXPath.parse(DefaultXPath.java:360)
	at org.dom4j.xpath.DefaultXPath.<init>(DefaultXPath.java:59)
	at org.dom4j.DocumentFactory.createXPath(DocumentFactory.java:230)
	at org.dom4j.tree.AbstractNode.createXPath(AbstractNode.java:207)
	at org.dom4j.tree.AbstractNode.selectSingleNode(AbstractNode.java:183)
	at org.rundeck.api.parser.JobsImportResultParser.parseXmlNode(JobsImportResultParser.java:46)

the JobsImportResultParser's xpath is using the rootXpath(),which content:
```
private String rootXpath() {
        return getApiVersion() < Version.V11.getVersionNumber() ? "result" : "";
    }
```
Maybe we can replace "" with "/"？

**Comment by gschueler** [comment]
bug cause: import jobs result should always expect "result" as root element for xpath purposes.
